# deployes the website at ./website
name: Build and Deploy Docs

on:
  push:
    branches:
      - main

env:
  BASE_URL: /react-ui/

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        # with:
        # node-version-file: '.nvmrc'

      - name: Install dependecies and build
        run: |
          cd reactui-docs/
          npm install
          CI=false npm run build

      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: reactui-docs/build # The folder the action should deploy
